version: '3'
services:
  web:
      build: .
      container_name: media.crawler
      command: bash -c "yarn && tail -f /dev/null"
      volumes:
        - .:/usr/src
        - /usr/src/node_modules
      ports:
        - "3006:3006"
      depends_on:
        - dynamodb
      networks:
        - infra_cdn

  dynamodb:
    image: dwmkerr/dynamodb
    ports:
      - "8000:8000"

networks:
  infra_cdn:
    external: true
