version: '3'
services:
  web:
      build: .
      container_name: media.crawler
      command: bash -c "yarn && tail -f /dev/null"
      volumes:
        - .:/usr/src
        - /usr/src/node_modules
      ports:
        - "3005:3005"
