version: '3'
services:
  mongo:
    image: mongo:3.6
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27018:27017"

  analyzer:
    build: .
    container_name: media.analyzer
    command: bash -c "tail -f /dev/null"
    volumes:
      - .:/usr/analyzer
      - /usr/analyzer/node_modules
    ports:
      - "3005:3005"
      - "3006:3006"
